# Generated by Django 5.2.3 on 2025-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stripe_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_publishable_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_webhook_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
