# Generated by Django 5.2.3 on 2025-07-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_company_stripe_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="stripe_enabled",
        ),
        migrations.RemoveField(
            model_name="company",
            name="stripe_publishable_key",
        ),
        migrations.RemoveField(
            model_name="company",
            name="stripe_secret_key",
        ),
        migrations.RemoveField(
            model_name="company",
            name="stripe_webhook_secret",
        ),
    ]
