# Generated by Django 5.2.3 on 2025-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_remove_company_stripe_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(db_index=True, max_length=255)),
                ("password", models.CharField(max_length=128)),
                (
                    "company_schema_name",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "company_schema_name"],
                        name="tenants_use_user_em_86b883_idx",
                    )
                ],
                "unique_together": {("user_email", "company_schema_name")},
            },
        ),
    ]
