# Generated by Django 5.2.3 on 2025-08-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_company_created_at_alter_company_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompany",
            name="last_login",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="usercompany",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
