# Generated by Django 5.2.3 on 2025-08-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_usercompany_last_login_alter_usercompany_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompany",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercompany",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usercompany",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usercompany",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
