# Generated by Django 5.2.3 on 2025-07-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitytemplate",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="activitytemplate",
            name="color_rgb",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
