# Generated by Django 5.2.3 on 2025-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activitytemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytemplate",
            name="color_rgb",
            field=models.CharField(
                choices=[
                    ("rgb(33, 37, 41)", "Dark"),
                    ("rgb(0, 108, 255)", "Blue"),
                    ("rgb(56, 184, 242)", "Azure"),
                    ("rgb(102, 16, 242)", "Indigo"),
                    ("rgb(111, 66, 193)", "Purple"),
                    ("rgb(232, 62, 140)", "Pink"),
                    ("rgb(220, 53, 69)", "Red"),
                    ("rgb(253, 126, 20)", "Orange"),
                    ("rgb(255, 193, 7)", "Yellow"),
                    ("rgb(192, 255, 0)", "Lime"),
                    ("rgb(40, 167, 69)", "Green"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
