# Generated by Django 5.2.3 on 2025-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_activitytemplate_color_rgb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitysession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitytemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitytemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
