# Generated by Django 5.2.3 on 2025-08-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_activitysession_updated_at_and_more"),
        ("clients", "0009_rename_checkout_session_clientplan_stripe_session_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("-reserved_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="clients.clientplan",
            ),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
    ]
