# Generated by Django 5.2.3 on 2025-08-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_reservation_options_and_more"),
        ("clients", "0009_rename_checkout_session_clientplan_stripe_session_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("session", "client_plan")},
        ),
    ]
