# Generated by Django 5.2.3 on 2025-08-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_reservation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancelled_at",
            field=models.DateTimeField(null=True),
        ),
    ]
