# Generated by Django 5.2.3 on 2025-08-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_reservation_cancelled_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("-session__date",)},
        ),
    ]
