# Generated by Django 5.2.3 on 2025-09-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_alter_reservation_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="checked_in",
        ),
    ]
