# Generated by Django 5.2.3 on 2025-09-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_remove_reservation_checked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="checked_in",
            field=models.DateTimeField(null=True),
        ),
    ]
