# Generated by Django 5.2.3 on 2025-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_reservation_checked_in"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytemplate",
            name="locations",
            field=models.ManyToManyField(to="locations.location"),
        ),
    ]
