# Generated by Django 5.2.3 on 2025-07-15 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("unlimited", "Unlimited"),
                            ("fixed_sessions", "Fixed number of sessions"),
                            ("fixed_days", "Fixed number of days"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "validity_type",
                    models.CharField(
                        choices=[
                            ("no_expiry", "No expiry"),
                            ("from_purchase", "From purchase date"),
                            ("from_first_use", "From first use"),
                            ("calendar_month", "By calendar month"),
                            ("fixed_date", "Fixed date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fixed_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
