# Generated by Django 5.2.3 on 2025-07-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="validity_duration_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="validity_duration_months",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="plan",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("unlimited", "Ilimitado"),
                    ("fixed_sessions", "Número fijo de sesiones"),
                    ("fixed_days", "Número fijo de días"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="validity_type",
            field=models.CharField(
                choices=[
                    ("no_expiry", "Sin vencimiento"),
                    ("from_purchase", "Desde la fecha de compra"),
                    ("from_first_use", "Desde el primer uso"),
                    ("calendar_month", "Por mes calendario"),
                    ("fixed_date", "Fecha fija"),
                ],
                max_length=20,
            ),
        ),
    ]
