# Generated by Django 5.2.3 on 2025-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_validity_duration_days_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
