# Generated by Django 5.2.3 on 2025-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plan_options_alter_plan_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
