# Generated by Django 5.2.3 on 2025-07-15 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField(auto_now_add=True)),
                ("first_use_date", models.DateField(blank=True, null=True)),
                (
                    "remaining_sessions",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="clients.client",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_plans",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Plan",
                "verbose_name_plural": "Client Plans",
            },
        ),
    ]
