# Generated by Django 5.2.3 on 2025-07-16 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_clientplan_created_at_clientplan_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientplan",
            name="cancellation_comments",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientplan",
            name="cancelled_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="clientplan",
            name="cancelled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
