# Generated by Django 5.2.3 on 2025-07-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientplan_cancellation_comments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientplan",
            options={
                "ordering": ["-id"],
                "verbose_name": "Client Plan",
                "verbose_name_plural": "Client Plans",
            },
        ),
    ]
