# Generated by Django 5.2.3 on 2025-07-19 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_clientplan_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="user_id",
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="source",
            field=models.CharField(
                choices=[("admin_panel", "Admin panel"), ("mobile_app", "App móvil")],
                max_length=100,
                null=True,
            ),
        ),
    ]
