# Generated by Django 5.2.3 on 2025-07-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_remove_client_user_id_client_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientplan",
            name="expires_at",
        ),
    ]
