# Generated by Django 5.2.3 on 2025-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_remove_clientplan_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientplan",
            name="checkout_session",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
