# Generated by Django 5.2.3 on 2025-07-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_clientplan_checkout_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientplan",
            old_name="checkout_session",
            new_name="stripe_session_id",
        ),
    ]
