# Generated by Django 5.2.3 on 2025-07-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_clientplan_options"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="customer_plan",
        ),
        migrations.AddField(
            model_name="payment",
            name="client_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="clients.clientplan",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("cash", "Efectivo"),
                    ("paypal", "PayPal"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
