# Generated by Django 5.2.3 on 2025-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
    ]
