# Generated by Django 5.2.3 on 2025-08-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_companysettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="app_banner",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
